### ISSUE TITLE
Security Checklist

### ISSUE THREAD

**Issue by shayanpg** [shayanpg/zoetrope#19]
- [ ] All inputs are sanitized / handled by templating
- [ ] Go through django deployment checklist [here](https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/)
- [ ] Create actual secret key, store correctly
- [ ] Debug == False
- [ ] Encryption and Integrity for API Keys
